# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  keycloak:
    container_name: oidc-oneid-keycloak
    image: quay.io/keycloak/keycloak:21.0.1
    command: ['start-dev --import-realm --log-level=DEBUG']
    volumes:
      - ./keycloak-properties/realm-config:/opt/keycloak/data/import
      - ./keycloak-properties/custom-idp-properties:/opt/keycloak/providers
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts,token-exchange,preview
      KC_HTTP_PORT: 9080
      KC_HTTPS_PORT: 9443
      ROOT_LOGLEVEL: DEBUG
      KEYCLOAK_LOGLEVEL: DEBUG
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:9443:9443
